# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18MyCRDltgCBsA97tgoKhSlodzD3MFtrl

1.   ARAFANG SANNEH
2.   MUHAMMED L DAFFEH
3.   ASAD

EXPLORATORY DATA ANALYSIS (EDA) WITH PANDAS

### 1. Import pandas library

This cell imports the pandas library, which is essential for data manipulation and analysis in Python. It's aliased as `pd` for convenience.
"""

import pandas as pd

"""### 2. Load the dataset

This cell loads the `movies_data.csv.xls` file into a pandas DataFrame named `df`. This is the first step in bringing our data into the notebook for analysis.
"""

df = pd.read_csv("/content/movies_data.csv.xls")

"""### 3. Display the first 2 rows of the DataFrame

`df.head(2)` is used to quickly inspect the first two rows of the DataFrame. This helps to understand the structure of the data, the column names, and the types of values present.
"""

df.head(2)

"""### 4. Check the shape of the DataFrame

`df.shape` returns a tuple representing the dimensionality of the DataFrame (number of rows, number of columns). This gives a quick overview of the dataset size.
"""

df.shape

"""### 5. Display column names

`df.columns` provides a list of all column names in the DataFrame. This is useful for understanding the available features and for referencing them in subsequent operations.
"""

df.columns

"""### 6. Get concise summary of the DataFrame

`df.info()` prints a concise summary of the DataFrame, including the index dtype and column dtypes, non-null values, and memory usage. This is crucial for identifying missing values and understanding data types.
"""

df.info()

"""### 7. Check for missing values

`df.isnull().sum()` calculates the number of missing (null) values for each column. This helps identify columns with incomplete data that might require cleaning.
"""

df.isnull().sum()

"""### 8. Handle missing values

This cell first drops rows where critical columns (`release_date`, `poster_path`, `overview`, `backdrop_path`) have missing values, as these are important for movie data. Then, it fills any remaining null values in the entire DataFrame with `0`. This ensures that all entries have a value and prevents potential errors in further analysis.
"""

df = df.dropna(subset=["release_date", "poster_path", "overview", "backdrop_path"])
df.fillna(0, inplace=True)

"""### 9. Check for duplicate rows

`df.duplicated().sum()` counts the total number of duplicate rows in the DataFrame. Identifying and handling duplicates is an important step in data cleaning to ensure data integrity.
"""

df.duplicated().sum()

"""### 10. Remove duplicate rows

`df.drop_duplicates()` removes any identified duplicate rows from the DataFrame, keeping only the first occurrence by default. This ensures that each movie entry is unique.
"""

df = df.drop_duplicates()

"""### 11. Generate descriptive statistics

`df.describe()` generates descriptive statistics that summarize the central tendency, dispersion, and shape of a dataset's distribution for numerical columns, excluding `NaN` values. This gives a quick overview of the data's statistical properties.
"""

df.describe()

"""### 12. Display value counts for key numerical columns

This cell calculates and displays the frequency of unique combinations of `popularity`, `vote_average`, and `vote_count`. This helps in understanding the distribution and common patterns within these specific numerical features.
"""

df[["popularity", "vote_average", "vote_count"]].value_counts()

"""### 13. Plot histogram of `vote_average`

This code generates a histogram of the `vote_average` column using `matplotlib.pyplot`. A histogram visually represents the distribution of numerical data, showing how frequently different `vote_average` scores appear. The `bins=20` argument divides the data into 20 intervals.
"""

import matplotlib.pyplot as plt

df["vote_average"].hist(bins=20)
plt.title("Vote Average Distribution")
plt.show()

"""### 14. Calculate correlation matrix

This cell calculates the pairwise correlation between `popularity`, `vote_average`, and `vote_count`. The correlation matrix helps in understanding the linear relationship between these numerical variables. Values close to 1 indicate a strong positive correlation, values close to -1 indicate a strong negative correlation, and values close to 0 indicate a weak or no linear correlation.
"""

df[["popularity", "vote_average", "vote_count"]].corr()

"""### 15. Plot scatter plot of `popularity` vs `vote_count`

This cell generates a scatter plot to visualize the relationship between `popularity` and `vote_count`. Each point on the plot represents a movie, with its x-coordinate being its popularity and its y-coordinate being its vote count. Scatter plots are useful for identifying trends, correlations, or clusters between two numerical variables.
"""

plt.scatter(df["popularity"], df["vote_count"])
plt.xlabel("popularity")
plt.ylabel("vote_count")
plt.title("Popularity vs Vote Count Scatter Plot")
plt.show()

"""### 16. Identify top 5 movies by popularity

This cell uses the `nlargest()` method to select the top 5 movies based on their 'popularity' score. It then displays only the 'title' and 'popularity' columns of these top movies, providing a quick summary of the most popular films in the dataset.
"""
